rticonnextdds-connector.js

We forgot to do this on the Js connector. That's why install testing failed on the vanilla Windows machine.

CON-93: Load VC runtime on Windows

---

test/nodejs/test_rticonnextdds_data_access.js

Some items had been added to a JSON object but not in the other
JSON object we were checking. This ocurred when adding support for
CON-177

CON-173: Fixed unit tests which were failing

---

test/nodejs/test_rticonnextdds_connector.js
test/xml/TestConnector.xml

@alexcamposruiz Confirmed that this test currently fails. Tested it with a librtiddsconnectord.so from develop (containing some initial changes in a feature branch to address this bug) and it passes.

CON-214: Test for creating Connector with participant_qos

---

test/nodejs/test_rticonnextdds_data_access.js
test/nodejs/test_rticonnextdds_input.js

Some of the unit tests were requiring the ffi modules to test the ability
to extend the API. Since we updated package.json to use the ffi-napi module,
the ffi module is no longer present and these tests were failing.

GREEN-1938: Use the ffi-napi modules in tests

---

rticonnextdds-connector.js

Tested on raspbuntu machine:
```
[sam@raspbuntu ~/connector-js-test-armv8]$ node node_modules/rticonnextdds-connector/examples/nodejs/simple/reader.js 
internal/fs/utils.js:230
throw err;
^
Error: ENOENT: no such file or directory, open '/home/sam/connector-js-test-armv8/node_modules/rticonnextdds-connector/rticonnextdds-connector/lib/armv8Linux4gcc7.3.0/librtiddsconnector.so'
at Object.openSync (fs.js:458:3)
at readFileSync (fs.js:360:35)
at new DynamicLibrary (/home/sam/connector-js-test-armv8/node_modules/ffi-napi/lib/dynamic_library.js:68:23)
at Object.Library (/home/sam/connector-js-test-armv8/node_modules/ffi-napi/lib/library.js:47:10)
at new _ConnectorBinding (/home/sam/connector-js-test-armv8/node_modules/rticonnextdds-connector/rticonnextdds-connector.js:104:20)
at …
```

CON-174: Handle armv8 architectures

---

rticonnextdds-connector.js
test/nodejs/test_rticonnextdds_connector.js

The behaviour of max_objects_per_thread has changed in the core, and it now
grows dynamically, meaning we no longer need to provide a way of setting it.

CON-223: Removed max_objects_per_thread API

---

docs/connector.rst
rticonnextdds-connector.js
test/nodejs/test_rticonnextdds_connector.js

CON-92: Added APIs to obtain versions used by Connector

---

.eslintrc.json
docs/conf.py
docs/copyright_license.rst
docs/data.rst
docs/index.rst
package-lock.json
package.json
rticonnextdds-connector.js
test/nodejs/test_rticonnextdds_connector.js
test/nodejs/test_rticonnextdds_data_access.js
test/nodejs/test_rticonnextdds_data_iterators.js
test/nodejs/test_rticonnextdds_dataflow.js
test/nodejs/test_rticonnextdds_discovery.js
test/nodejs/test_rticonnextdds_events.js
test/nodejs/test_rticonnextdds_input.js
test/nodejs/test_rticonnextdds_metadata.js
test/nodejs/test_rticonnextdds_output.js
test/xml/TestConnector.xml

@alexcamposruiz This contains changes from PR https://github.com/rticommunity/rticonnextdds-connector-js/pull/59 and https://github.com/rticommunity/rticonnextdds-connector-js/pull/63 and PR https://github.com/rticommunity/rticonnextdds-connector-py/pull/83
One of the changes in those PRs was for CON-227, to fix a broken API.
The rest of the changes added some npm scripts + fixed formatting of code.
I do not know if we want the second of these changes in the HM release or not, if not let me know and I'll remove it (I kept it in for now since it means I don't have to manually revert them).

CON-190, CON-191, CON-178, CON-226, CON-227, CON-184 merge to 1.2.0

---

docs/release_notes.rst

Adding support for macOS 11 in the release notes.
I redid my changes in a new branch that's based off of develop.

PLATFORMS-2289. Adding macOS 11 to Connector JS in develop

---

docs/release_notes.rst

This isn't a cherry-pick from dev, but has same content changes.

Feature/platforms-2289 add macos 11 to Connector JS 1.2.0 release notes

---

test/nodejs/test_rticonnextdds_connector.js
test/xml/TestConnector.xml

* HMAINT-235: Handle case where build ID has 4 integers
* HMAINT-235: Fix unrelated commented out test
(cherry picked from commit 2ae970264dc1c772fa91e20bf4e53e93a6bdcc53)

Feature/hmaint 235 (#76)

---

docs/configuration.rst
docs/connector.rst
docs/data.rst
docs/features.rst
docs/index.rst
docs/input.rst

We should make links to core docs go to the specific release. Otherwise, some day when Connector 1.2.0 is old, its links will still go to the latest version of Pro docs, and these may not be appropriate.

CON-252: updating links from current to 6.1.1, js

---

docs/copyright_license.rst
docs/data.rst
docs/release_notes.rst
rticonnextdds-connector.js

Make sure I put the new features/fixes in the right product (e.g., CON-209 is python only)
Will do these in separate PRs coming up:
- CON-234 (fix broken link)
- CON-252 (links to core docs should use release number, not 'current')
- Should we send copyright_license.rst page to Legal for review? Or do you know for a fact that hasn't changed?

CON-251: connector js release notes for 6.1.1/1.2.0

---

docs/release_notes.rst

cherry-picking what I did in develop to release branch now. Here was the PR to develop: https://github.com/rticommunity/rticonnextdds-connector-js/pull/92

CON-251: added missing release note

---

package-lock.json

This corrects the changes to package-lock.json when using a new version of npm. This was created using npm 6.13.3.

HMAINT-202 -- use npm v6 to update package-lock.json

---

docs/features.rst
docs/getting_started.rst
docs/release_notes.rst

* CON-254: Document unsupport Node.JS v11
* CON-254: PR feedback
* Update docs/release_notes.rst
Co-authored-by: Alex Campos <alejandro@rti.com>
* CON-254: PR Feedback
* CON-254. Updating Supported Platforms ro match the PAM for 6.1.1.
* CON-254. Updating supported platforms.
Co-authored-by: Alex Campos <alejandro@rti.com>
Co-authored-by: adelleolson <adelle@rti.com>
(cherry picked from commit 5fe2b519bf58463ff9339315ececd3aa4a3c0391)

CON-254: Document unsupport Node.JS v11 (#93)

---

package-lock.json
package.json

updating libraries for candidate release rc6. This will be used as a test release for 1.2.0. Here are _BUILD_ strings:
Z-1510 | for i in */*.so */*.dll */*.dylib  ; do strings $i | grep _BUILD_ && echo found in $i; done
NDDSC_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm/libnddsc.so
NDDSCORE_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm/libnddscore.so
RTICONNECTOR_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm/librtiddsconnector.so
NDDSC_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm64/libnddsc.so
NDDSCORE_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm64/libnddscore.so
RTICONNECTOR_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm64/librtiddsconnector.so
NDDSC_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in …

#fix HMAINT-202 -- new connector libraries for js, base on DDS 6.1.1 (20220309, bkprt)

---

.github/dependabot.yml

See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#disabling-dependabot-version-updates
I think that to begin with we only want dependabot to report vulnerabilities. If we don't set this it will report for out-of-date dependencies.
See:
https://github.com/rticommunity/rticonnextdds-connector-js/pull/118
https://github.com/rticommunity/rticonnextdds-connector-js/pull/119
https://github.com/rticommunity/rticonnextdds-connector-js/pull/120
https://github.com/rticommunity/rticonnextdds-connector-js/pull/121
https://github.com/rticommunity/rticonnextdds-connector-js/pull/122
If this PR is accepted I will close those PRs

Update dependabot config to not create PRs for bumping deps

---

docs/getting_started.rst
docs/release_notes.rst

Added v18 to supported versions of Node
Fixed our docs about node-gyp requirements.
For more details:
Removed recommendation to install windows-build-tools since it is no longer required with modern Node.JS versions (source: https://www.npmjs.com/package/windows-build-tools)
Removed specific version of Python/GCC. We were stating the Python2.7 is needed, which hasn't been true for a long time (see CON-260 description).

CON-261 CON-260: Document support node v18 + update node-gyp requirements

---

docs/conf.py
package-lock.json
package.json

Updated git library links to the latest build in the common library repository. Changed docs version to 1.2.2 and bump the rc version to rc2.

CON-278 -- rc2 with libraries from 20221028

---

docs/getting_started.rst
docs/release_notes.rst

Updated documentation to note the known limitations of CON-277 and CON-262.
CON-277: Versions of Node.js >= 18.8.0 are unsupported.
CON-262: Versions of npm >= v7 are not able to install Connector via a github URL.
In order to document CON-262, I simply removed the documentation that lists `npm install <github_url>` as a valid method of installation.

CON-282: Document known limitations

---

docs/getting_started.rst
docs/release_notes.rst

(cherry picked from commit 03897d71528c9b25dea7b3c85a049448e334bd66)

CON-282: Document known limitations (#141)

---

package-lock.json
package.json

Removing the -rcX from the version string and ran "npm i --package-lock-only". Double checked libraries and they are all pointing to build NDDSCORE_BUILD_6.1.2.0_20221111T000000Z_RTI_REL.

CON-278 -- final version string for 1.2.2

---

package-lock.json
package.json

Update package.json to remove all devDependencies that are not needed to run the unit tests.
There were multiple dependencies listed there that were used for linting and code coverage. Also removed the npm scripts that used these dependencies.
There is no automation at RTI that uses these npm scripts.
It is still possible to run a linter / code coverage if desired (but we are not explicitly listing any versions as dependencies).
The motivation for this was to reduce our potential exposure to vulnerabilities in third party packages.

CON-290: Removed multiple dependencies of Connector

---

docs/data.rst
docs/release_notes.rst

The original task here was to remove the limitation on Windows usage of "Infinity" since we now ship VS2015 as base.
After some investigation, I decided that the current level of support that we have for "Infinity", "-Infinity" and "-0" leaves a lot to be desired (see Fabrizio's article here: https://community.rti.com/kb/advanced-data-access-using-connector-javascript).
So I decided to just remove all mention of it completely and a add a disclaimer that there are some gotchas to be aware of if using that functionality.
New docs:

CON-248: Add warning regarding the use of Infinity

---

docs/conf.py
docs/configuration.rst
docs/connector.rst
docs/data.rst
docs/features.rst
docs/getting_started.rst
docs/index.rst
docs/input.rst
docs/release_notes.rst
package-lock.json
package.json

This will update several documentation links in support/connector/1.2.0. It will also change the version to 1.2.2. This also updates the rticonnextdds-connector submodule to a commit with the latest libraries having build id: NDDSCORE_BUILD_6.1.2.0_20221111T000000Z_RTI_REL.

Merge release/connector/1.2.2 to support/connector/1.2.0

---

Dockerfile
Jenkinsfile

To fix COMMUNITY-69 I added `--network none` to the docker run arguments to avoid interferences among the tests.
To fix COMMUNITY-70 I created a new directory (`/opt/node_deps`) inside the container and set it as the npm prefix.

COMMUNITY-69 & COMMUNITY-70 | add network isolation for tests containers and fix doc generation

---

docs/release_notes.rst

With the latest changes, a broader range of Node versions are supported. The Release Notes should reflect this.

Update Release Notes on supported Node versions

---

.github/workflows/build_doc.yaml

The only part that we need from that string is the version digits (X.Y.Z) the other characters should be filtered-out.

COMMUNITY-71 | Remove the -doc suffix from the version string when it is obtained from the tag

---

.github/workflows/build_doc.yaml

* COMMUNITY-72: fix secret name
* COMMUNITY-72: change s3 upload action
* Revert "COMMUNITY-72: change s3 upload action"
This reverts commit 42484fef8b88b5c109d4623db63bfd5a862639f8.
* COMMUNITY-72: specify endpoint to the action
* COMMUNITY-72: add double commas
* COMMUNITY-72: fix syntax
* COMMUNITY-72: replace the action with the s3 CLI
* COMMUNITY-72: make doc public when it is published

COMMUNITY-72 | Fix documentation publication to AWS S3 (#176)

---

.github/workflows/build.yaml

The removal of this trigger will avoid accidental publications.

COMMUNITY-77 | Remove tag trigger to publish to npm registry

---

examples/nodejs/web_socket/indexMaps.html

The URL of the CDN used for this dependency has been broken for some time, and it's now been fixed.

CON-287: Update OpenLayers dependency in web_socket's Map example.

---

ci_config.yaml

This could avoid some CI failures in the future if node introduces breaking changes.
Close #195 
List of node versions and its names: https://nodejs.org/en/about/previous-releases

Use the current lts instead of the latest one

---

docs/release_notes.rst

CON-311: Add warning to documentation

---

README.md
README.rst
package-lock.json
package.json
rticonnextdds-connector.js
test/nodejs/test_rticonnextdds_data_access.js
test/nodejs/test_rticonnextdds_dataflow.js
test/nodejs/test_rticonnextdds_discovery.js
test/nodejs/test_rticonnextdds_input.js

As described in issue https://github.com/rticommunity/rticonnextdds-connector-js/issues/198, the javascript connector is no longer compatible with newer versions of `Node` due to the [ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi) package not being compatible.
[ffi-nap](https://github.com/node-ffi-napi/node-ffi-napi) seems no longer being maintained given that the last contribution is from more than two years ago.
An alternative package that provides similar functionallity is [koffi](https://koffi.dev/). The syntax is very similar to `ffi-napi` and is currently actively being maintained.
This MR migrates from `ffi-napi` to `koffi` library, removing the need for the incompatible `ffi-napi` package.
I have tested these changes with v1.3.0 and v1.2.2 of the RTIConnextDDS-Connector …

refactor: migrate from ffi-napi to koffi for foreign function calls

---

docs/getting_started.rst

I originally created this PR to release/connector/1.3.1 ([here](https://github.com/rticommunity/rticonnextdds-connector-js/pull/214)), but that was wrong. Connector 1.3.1 is associated with Connext 7.3.0.2 and is final. Any future changes I need to make to Connector documentation for next releases need to happen in develop and support/connector/1.3.0. 
I have cherry-picked the commit in the defunct PR to this one.
Note: Python and C# have a similar issue. Those doc changes have already been made in [this PR](https://bitbucket.rti.com/projects/CONNEXT/repos/connextdds/pull-requests/19705/overview).
The doc output associated with this PR is here: https://jenkins-community.rti.com/job/ci/job/connector-js/job/rticonnextdds-connector-js-doc/view/change-requests/job/PR-215/Connector_20Documentat …

DOC-585: updating Connector getting started instructions to mention <version>

---

docs/getting_started.rst

Cherry-picking this PR: https://github.com/rticommunity/rticonnextdds-connector-js/pull/215
The doc output associated with this PR is here: https://jenkins-community.rti.com/job/ci/job/connector-js/job/rticonnextdds-connector-js-doc/view/change-requests/job/PR-221/Connector_20Documentation/getting_started.html

DOC-611: updating Connector getting started instructions to mention <version> (backporting DOC-585)

---

docs/conf.py
docs/copyright_license.rst

Updated copyright year in conf.py
Updated copyright year and text in copyright_license.rst
[Doc output](https://jenkins-community.rti.com/job/ci/job/connector-js/job/rticonnextdds-connector-js-doc/view/change-requests/job/PR-222/Connector_20Documentation/copyright_license.html#)

DOC-532: Update Connector copyrights

---

rticonnextdds-connector.js

Output log: [CON-275_test.log](https://github.com/user-attachments/files/18007308/CON-275_test.log)

CON-275: Add initial support for osx-arm64

---

docs/input.rst
rticonnextdds-connector.js
test/nodejs/test_rticonnextdds_data_access.js

* Added new `returnSamples` method to `Input` class.
This requires accessing a new native function, thus requires new native libraries.
You can see the accompanying PR for Python rticommunity/rticonnextdds-connector-py#179.

CON-326: Allow returning samples, enhance wait to be able to return samples before actually waiting.

---

docs/release_notes.rst
rticonnextdds-connector.js

We're changing some of the platforms that are bundled with Connector. As such, we need to update the library loading mechanism and the platform notes.

CON-334: Update Platform Support

---

examples/nodejs/web_socket/indexMaps.html

As it happened in the past (see #185), the CDN for the Maps Example stopped working for some reason.
For this reason, I've bumped up the version of OpenLayers CDN package from 6.0.1 to 6.15.1, which is available in the same CDN.

Change the CDN path for OpenLayers HTML dependency
