rticommunity/rticonnextdds-connector-js

- examples/nodejs/web_socket/README.md
Some feedback from install testing
> Update README in web socket example

- docs/getting_started.rst
- docs/release_notes.rst
Issue described here: https://stackoverflow.com/a/62352383
> Update minimum supported version of node v10 in docs

- docs/features.rst
> Document dependency on Connext version from dynamic libs

- docs/copyright_license.rst
required by Legal (they don't care where we put it as long as it's in there)
> HERCULES-186: updates to licenses doc for javascript

- .eslintrc.json
- package-lock.json
- package.json
- rticonnextdds-connector.js
- test/nodejs/test_rticonnextdds_connector.js
Generated the linting config file with the following configuration:
sam@rti-10678:~/working/trees/connector/rticonnextdds-connector-js$ eslint --init
✔ How would you like to use ESLint? · style
✔ What type of modules does your project use? · commonjs
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · node
✔ How would you like to define a style for your project? · guide
✔ Which style guide do you want to follow? · standard
✔ What format do you want your config file to be in? · JSON
> Fixed linting problems + committed the lint config file.

- docs/conf.py
From PR https://github.com/rticommunity/rticonnextdds-connector-js/pull/66
> CORE-11993 to 1.1.1 branch

- docs/conf.py
- package.json
Final version string for release 1.1.1
> feature/support 308 version, change version to 1.1.1

- docs/data.rst
> CON-246: Added warning about inf and Nan on windows

- docs/conf.py
- docs/release_notes.rst
- package-lock.json
- package.json
Updates from 1.1.1 back to master
> Updates from 1.1.1 back to master

- docs/conf.py
- package.json
Corrected malformed version string.
> HMAINT-202, fix version string to start testing

- docs/conf.py
- package.json
I'd like to keep the version string in sync with py.
> HMAINT-202 -- set version to rc2 for testing

- docs/release_notes.rst
We forgot to add a release note (CON-157).
> CON-251: added missing release note

- docs/conf.py
- package-lock.json
- package.json
Changing version string from 1.2.0-rc2 to 1.2.0
> HMAINT-202 -- set version string to 1.2.0

- package-lock.json
- package.json
This has the corrected libraries from 20211203.
> #fix HMAINT-202 -- rc5 for testing on npm server

- package-lock.json
- package.json
Final version string change to 1.2.0.
> #fix HMAINT-202 -- final version string 1.2.0

- .eslintrc.json
- docs/conf.py
- docs/configuration.rst
- docs/connector.rst
- docs/copyright_license.rst
- docs/data.rst
- docs/features.rst
- docs/getting_started.rst
- docs/index.rst
- docs/input.rst
- docs/release_notes.rst
- package-lock.json
- package.json
- rticonnextdds-connector.js
- test/nodejs/test_rticonnextdds_connector.js
- test/nodejs/test_rticonnextdds_data_access.js
- test/nodejs/test_rticonnextdds_data_iterators.js
- test/nodejs/test_rticonnextdds_dataflow.js
- test/nodejs/test_rticonnextdds_discovery.js
- test/nodejs/test_rticonnextdds_events.js
- test/nodejs/test_rticonnextdds_input.js
- test/nodejs/test_rticonnextdds_metadata.js
- test/nodejs/test_rticonnextdds_output.js
- test/xml/TestConnector.xml
master updated with the 1.2.0 release.
> Final merge of release 1.2.0 to master.

- docs/release_notes.rst
Also showed Jose the proposed release notes and he agreed.
> CON-264: Added release notes for 1.2.1 release

- docs/release_notes.rst
- package-lock.json
Contains new release notes + dependabot version bumps
> 1.2.1 release changes

- docs/conf.py
- package-lock.json
- package.json
> #fix BUILD-3375 -- set release to 1.2.1

- docs/conf.py
- docs/getting_started.rst
- docs/release_notes.rst
- package-lock.json
- package.json
Address expected merge conflicts from source branch release/connector/1.2.1 to destination branch master: docs/conf.py, docs/release_notes.rst, package-lock.json and package.json. All changes relevant to 1.2.1.
> Merge release/connector/1.2.1 back to master.

- rticonnextdds-connector.js
(cherry picked from commit 970663c754b20f933b2dd1ae05387e4a292fadb6)
> CON-276: Updated loading of redist + commit of submodule (#132)

- package-lock.json
- package.json
Update package.json version string to 1.2.2
> CON-281-support, change version number to 1.2.2 in support/connector/1.2.0

- package-lock.json
- package.json
Move submodule pointer to new libraries. Set release to rc3 so we can test.
> CON-279 -- Update library pointer, and set release to rc3.

- docs/conf.py
- docs/configuration.rst
- docs/connector.rst
- docs/data.rst
- docs/features.rst
- docs/getting_started.rst
- docs/index.rst
- docs/input.rst
- docs/release_notes.rst
- package-lock.json
- package.json
- rticonnextdds-connector.js
feature branch based on master. Merged release/connector/1.2.2.
Several doc files have been updated. Packaging files and top rticonnextdds-connector.js change too.
> CON-285 merge docs and package info back to master.

- examples/nodejs/simple/writer.js
- package-lock.json
- package.json
- rticonnextdds-connector.js
Also, remove "sleep" as a dependency due to problems with Node v20.
> CON-299: Replace incompatible library

- docs/conf.py
- docs/configuration.rst
- docs/connector.rst
- docs/data.rst
- docs/features.rst
- docs/index.rst
- docs/input.rst
- docs/release_notes.rst
- test/xml/InvalidXml.xml
- test/xml/TestConnector2.xml
- test/xml/TestConnector3.xml
Update the doc/conf.py and doc/release_notes.rst to show new version 1.3.0.
> CON-298 -- Change mention of version string in doc/

- docs/release_notes.rst
Add release note CON-299 to Connector 1.3.0
> CON-299: Add 1.3.0 release note

- .github/workflows/build_doc.yaml
URL to successful test: https://github.com/ManuelJNunez/rticonnextdds-connector-js/actions/runs/7568742680/job/20610640176
> COMMUNITY-72 | Fix documentation publication to AWS S3

- examples/nodejs/web_socket/indexMaps.html
Updating `release/connector/1.3.0` branch with latest changes in `develop`.
> CON-287: Update 'maps' example dependency (#185) to release/connector/1.3.0

- ci_config.yaml
- resources/docker/Dockerfile
- resources/jenkins/build_and_test.groovy
- resources/scripts/publish.sh
In this PR I added a new stage to publish connector into our internal server when a new tag with format `v\d+\.\d+\.\d+` is pushed. That new stage will call a bash script that I implemented for that purpose.
> COMMUNITY-80 | Add a new stage in the build_and_test script to publish connector into our internal npm server when a new tag is pushed

- docs/release_notes.rst
Updated Platform Notes to reflect platform validation
> Update Platform Notes

- docs/release_notes.rst
Pulling most recent changes to documentation to the release branch.
> CON-305 to release branch

- docs/index.rst
- docs/release_notes.rst
Correct heading levels in releasenotes.rst
> DOC-489: Correct headings in Previous Releases section

- docs/release_notes.rst
Also, make minor fixes to Release Notes.
> CON-304 documentation changes (1.3.0)

- docs/release_notes.rst
You can see the output here: https://jenkins-community.rti.com/job/ci/job/connector-js/job/rticonnextdds-connector-js-doc/view/change-requests/job/PR-213/Connector_20Documentation/
> CON-318: add CON-318 to Connector 1.3.1 release notes for 7.3.0.2
